"""empty message

Revision ID: 481d4a3fef63
Revises: 16776b812c23
Create Date: 2014-08-14 21:53:54.312243

"""

# revision identifiers, used by Alembic.
revision = '481d4a3fef63'
down_revision = '16776b812c23'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('join',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('join')
    ### end Alembic commands ###
