"""empty message

Revision ID: 4f25e136d642
Revises: 2e11f81b3931
Create Date: 2014-08-06 02:02:44.756537

"""

# revision identifiers, used by Alembic.
revision = '4f25e136d642'
down_revision = '2e11f81b3931'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.drop_column('article', 'data_created')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('data_created', mysql.DATETIME(), nullable=True))
    op.drop_column('article', 'date_created')
    ### end Alembic commands ###
